[[constraint]]
  name = "cloud.google.com/go"
  version = "0.34.0"

[[constraint]]
  name = "github.com/apache/thrift"
  revision = "24918abba929282"
  source = "github.com/apache/thrift"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.1.2"

[prune]
  go-tests = true
  unused-packages = true
